title: Vespa Azwan # your name (or website title) here
logo: "/images/vz.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi there, I'm Vespa Azwan! 
  <br><br>
  I'm Web/Mobile apps Developer with 6 years of professional experience.
  <br><br>
  <a href="https://www.linkedin.com/in/vespa-azwan-7817b98a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-165414802-1 # your Google Analytics tracking ID here
